"""
Constraint Generator Module.

Generates ALTER TABLE statements for foreign keys and other constraints.
"""

import sys
from pathlib import Path
from typing import List

# Add project root to path if needed
project_root = Path(__file__).parent.parent.parent
if str(project_root) not in sys.path:
    sys.path.insert(0, str(project_root))

from src.models.base_table import BaseTable
from src.utils.logger import get_logger

logger = get_logger(__name__)


class ConstraintGenerator:
    """Generates constraint SQL statements (FK, PK, unique, etc.)."""
    
    def __init__(self):
        """Initialize constraint generator."""
        self.generated_constraints: List[str] = []
    
    def generate_foreign_keys(self, table: BaseTable) -> List[str]:
        """
        Generate ALTER TABLE statements for foreign keys.
        
        Args:
            table: Table model instance
            
        Returns:
            List of ALTER TABLE SQL statements for foreign keys
        """
        if not table.foreign_keys:
            logger.debug(f"No foreign keys defined for {table.table_name}")
            return []
        
        try:
            logger.info(f"Generating foreign keys for {table.get_full_table_name()}")
            
            sql_statements = table.get_foreign_key_sql()
            
            self.generated_constraints.extend([table.table_name] * len(sql_statements))
            logger.debug(f"Generated {len(sql_statements)} FK constraints")
            
            return sql_statements
            
        except Exception as e:
            logger.error(f"Failed to generate foreign keys for {table.table_name}: {e}")
            raise
    
    def generate_all_foreign_keys(self, tables: List[BaseTable]) -> List[str]:
        """
        Generate ALTER TABLE statements for foreign keys across all tables.
        
        Args:
            tables: List of table model instances
            
        Returns:
            List of ALTER TABLE SQL statements for all foreign keys
        """
        sql_statements = []
        
        for table in tables:
            try:
                fk_statements = self.generate_foreign_keys(table)
                sql_statements.extend(fk_statements)
            except Exception as e:
                logger.error(f"Skipping foreign keys for {table.table_name} due to error: {e}")
                continue
        
        logger.info(f"Generated {len(sql_statements)} total FK constraints")
        return sql_statements
    
    def generate_drop_foreign_key(self, table_name: str, constraint_name: str) -> str:
        """
        Generate ALTER TABLE DROP CONSTRAINT statement.
        
        Args:
            table_name: Full table name (schema.table)
            constraint_name: Constraint name to drop
            
        Returns:
            ALTER TABLE DROP CONSTRAINT SQL statement
        """
        sql = f"ALTER TABLE {table_name} DROP CONSTRAINT IF EXISTS {constraint_name}"
        logger.debug(f"Generated DROP CONSTRAINT: {sql}")
        return sql
    
    def save_to_file(self, sql_statements: List[str], filepath: str):
        """
        Save constraint SQL statements to a file.
        
        Args:
            sql_statements: List of SQL statements
            filepath: Output file path
        """
        try:
            with open(filepath, 'w') as f:
                f.write("-- Foreign Key Constraints\n")
                f.write("-- Generated by E-Commerce DWH Constraint Generator\n\n")
                
                for sql in sql_statements:
                    f.write(sql + ";\n\n")
            
            logger.info(f"Saved {len(sql_statements)} constraint SQL statements to {filepath}")
            
        except Exception as e:
            logger.error(f"Failed to save constraints to {filepath}: {e}")
            raise
