"""
Amazon Redshift DDL adapter.

Transforms BaseTable model definitions into Redshift-compatible DDL without
modifying existing Snowflake / PG / Databricks / BigQuery DDL logic.

Design decisions (see plans/phase13_redshift.md):
- 2-part qualified names (schema.table). Cross-database queries are not used
  by the loader; database is bound at connect time.
- Native semi-structured: VARIANT/OBJECT/ARRAY -> SUPER.
- Native geospatial: GEOGRAPHY / GEOMETRY passthrough.
- Binary -> VARBYTE.
- VARCHAR(n) preserved; clamped to 65535 (Redshift max) with a warning.
- TIMESTAMP_NTZ -> TIMESTAMP (no timezone).
- DISTSTYLE AUTO; no manual SORTKEY (decision Q5: AUTO across the board).
- PK inline informational; FK via separate ALTER TABLE statements (Q6).
- Comments via COMMENT ON TABLE / COMMENT ON COLUMN (Postgres-style).
- Identity columns: GENERATED BY DEFAULT AS IDENTITY(1,1) on surrogate keys.
"""

from typing import List, Optional, Tuple

from src.models.base_table import BaseTable, Column
from src.utils.logger import get_logger

logger = get_logger(__name__)


# Redshift VARCHAR maximum byte length.
RS_VARCHAR_MAX = 65535


def map_column_to_rs(col: Column) -> str:
    """
    Map a Snowflake column definition to a Redshift SQL column fragment.

    Returns the column clause without comments — comments are emitted as
    separate COMMENT ON statements (Postgres-style).
    """
    rs_type = _map_type(col.data_type, col.length, col.precision, col.scale)

    parts = [col.name, rs_type]

    if not col.nullable:
        parts.append("NOT NULL")

    if col.default is not None:
        parts.append(f"DEFAULT {col.default}")

    return " ".join(parts)


def _map_type(
    data_type: str,
    length: Optional[int],
    precision: Optional[int],
    scale: Optional[int],
) -> str:
    """Map Snowflake data type to Redshift equivalent."""
    dt = data_type.upper().strip()

    if dt == "VARCHAR":
        if length:
            if length > RS_VARCHAR_MAX:
                logger.warning(
                    f"VARCHAR({length}) exceeds Redshift maximum {RS_VARCHAR_MAX}; "
                    f"clamping."
                )
                return f"VARCHAR({RS_VARCHAR_MAX})"
            return f"VARCHAR({length})"
        return f"VARCHAR({RS_VARCHAR_MAX})"

    if dt == "NUMBER":
        if precision is not None and scale is not None and scale > 0:
            return f"NUMERIC({precision},{scale})"

        p = precision or 38

        # Redshift NUMERIC max precision is 38 (same as Snowflake), but for
        # surrogate keys and integer columns we prefer the native int types
        # for performance and storage. Snowflake's NUMBER(38,0) collapses to
        # BIGINT (19 digits) — same convention as the other adapters. Real
        # overflow risk is theoretical for our key ranges.
        if p == 38:
            return "BIGINT"
        if p <= 4:
            return "SMALLINT"
        if p <= 9:
            return "INTEGER"
        if p <= 18:
            return "BIGINT"
        # p in (19, 38) but not 38 → use NUMERIC.
        return f"NUMERIC({p},0)"

    if dt == "TIMESTAMP_NTZ":
        # Redshift TIMESTAMP has no timezone; matches TIMESTAMP_NTZ semantics.
        return "TIMESTAMP"

    if dt == "TIMESTAMP":
        return "TIMESTAMPTZ"

    if dt == "DATE":
        return "DATE"

    if dt == "TIME":
        return "TIME"

    if dt == "BOOLEAN":
        return "BOOLEAN"

    if dt in ("FLOAT", "DOUBLE"):
        return "DOUBLE PRECISION"

    # Semi-structured — native SUPER type on Redshift.
    if dt in ("VARIANT", "OBJECT", "ARRAY"):
        return "SUPER"

    if dt in ("BINARY", "VARBINARY"):
        return "VARBYTE"

    # Native geospatial.
    if dt == "GEOGRAPHY":
        return "GEOGRAPHY"
    if dt == "GEOMETRY":
        return "GEOMETRY"

    return dt


def generate_rs_create_table(
    table: BaseTable,
    schema: str,
) -> Tuple[str, List[str]]:
    """
    Generate Redshift CREATE TABLE statement and COMMENT statements.

    Args:
        table: BaseTable instance
        schema: Redshift schema name

    Returns:
        (create_sql, comment_statements) — comment_statements contains
        COMMENT ON TABLE and COMMENT ON COLUMN statements (Postgres-style).
        DISTSTYLE AUTO is appended; no manual SORTKEY.
    """
    qualified_name = f"{schema}.{table.table_name}"
    columns = table.define_columns()

    column_defs = [f"  {map_column_to_rs(col)}" for col in columns]

    if table.primary_key:
        pk_cols = ", ".join(table.primary_key)
        # Redshift accepts PK as informational; doesn't enforce. No NOT
        # ENFORCED keyword needed (and it's rejected if added).
        column_defs.append(f"  PRIMARY KEY ({pk_cols})")

    columns_sql = ",\n".join(column_defs)

    create_sql = (
        f"CREATE TABLE IF NOT EXISTS {qualified_name} (\n"
        f"{columns_sql}\n"
        f")\n"
        f"DISTSTYLE AUTO;"
    )

    comments: List[str] = []

    if table.comment:
        comments.append(
            f"COMMENT ON TABLE {qualified_name} IS '{_escape_rs(table.comment)}';"
        )

    for col in columns:
        if col.comment:
            comments.append(
                f"COMMENT ON COLUMN {qualified_name}.{col.name} "
                f"IS '{_escape_rs(col.comment)}';"
            )

    return create_sql, comments


def generate_rs_drop_table(table: BaseTable, schema: str) -> str:
    """Generate Redshift DROP TABLE statement."""
    return f"DROP TABLE IF EXISTS {schema}.{table.table_name} CASCADE;"


def generate_rs_foreign_keys(table: BaseTable, schema: str) -> List[str]:
    """
    Generate Redshift ALTER TABLE FK statements.

    Redshift accepts but does not enforce foreign keys — the planner uses
    them for join elimination and rewrite. ON DELETE / ON UPDATE clauses
    are omitted because Redshift FKs cannot cascade.
    """
    statements: List[str] = []
    qualified_name = f"{schema}.{table.table_name}"

    for fk in table.foreign_keys:
        constraint_name = fk.constraint_name or f"fk_{table.table_name}_{fk.column}"
        ref_table = f"{schema}.{fk.reference_table.lower()}"

        sql = (
            f"ALTER TABLE {qualified_name} "
            f"ADD CONSTRAINT {constraint_name} "
            f"FOREIGN KEY ({fk.column}) "
            f"REFERENCES {ref_table}({fk.reference_column});"
        )
        statements.append(sql)

    return statements


def generate_rs_create_schema(schema: str) -> str:
    """Generate CREATE SCHEMA IF NOT EXISTS for Redshift."""
    return f"CREATE SCHEMA IF NOT EXISTS {schema};"


def _escape_rs(text: str) -> str:
    """Escape single quotes for Redshift string literals."""
    return text.replace("'", "''")
