"""
Dimension generator for dim_customers.

Generates customer profile records (identity + demographics) with SCD Type 2 support.
Address data is generated by DimCustomerAddressGenerator.
Loyalty data is generated by DimCustomerLoyaltyGenerator.
"""

import random
from datetime import datetime, date
from typing import List, Optional

from .base_entity import BaseEntityGenerator, GeneratedData


class DimCustomersGenerator(BaseEntityGenerator):
    """Generator for dim_customers table (SCD Type 2) - profile data only."""

    table_name = "dim_customers"

    PREFERRED_CHANNELS = ["Online Web", "Mobile App", "In-Store", "Phone Order"]

    def generate(
        self,
        count: int = 1000,
        start_key: int = 1,
        segment_keys: List[int] = None,
        effective_date: Optional[date] = None,
        **kwargs
    ) -> GeneratedData:
        """
        Generate customer profile dimension records.

        Args:
            count: Number of customers to generate
            start_key: Starting surrogate key value
            segment_keys: List of valid segment keys
            effective_date: SCD effective date

        Returns:
            GeneratedData with customer dimension records
        """
        if count <= 0:
            return GeneratedData(
                table_name=self.table_name,
                data=self._create_dataframe([]),
                surrogate_keys=[]
            )

        self.logger.info(f"Generating {count} customers")

        if not segment_keys:
            segment_keys = list(range(1, 8))

        eff_date = effective_date or self.config.dates.start
        end_date = date(9999, 12, 31)

        records = []
        keys = []
        now = datetime.now()

        for i in range(count):
            key = start_key + i
            keys.append(key)

            first_name = self.faker.first_name()
            last_name = self.faker.last_name()

            email_domain = random.choice([
                "gmail.com", "yahoo.com", "outlook.com", "icloud.com", "hotmail.com"
            ])
            email = f"{first_name.lower()}.{last_name.lower()}{random.randint(1, 999)}@{email_domain}"

            segment_weights = [0.05, 0.15, 0.30, 0.30, 0.10, 0.07, 0.03]
            segment_key = random.choices(
                segment_keys,
                weights=segment_weights[:len(segment_keys)]
            )[0]

            birth_date = self.faker.date_of_birth(minimum_age=18, maximum_age=80)

            record = {
                "customer_key": key,
                "customer_id": f"CUST{key:08d}",
                "first_name": first_name,
                "last_name": last_name,
                "full_name": f"{first_name} {last_name}",
                "email": email,
                "phone_number": self.faker.numerify("+1-###-###-####"),
                "birth_date": birth_date,
                "gender": random.choice(["M", "F", "O", None]),
                "segment_key": segment_key,
                "preferred_channel": random.choice(self.PREFERRED_CHANNELS),
                "is_active": True,
                # SCD Type 2 columns
                "effective_date": eff_date,
                "end_date": end_date,
                "is_current": True,
                "created_at": now,
                "updated_at": now,
            }
            records.append(record)

        df = self._create_dataframe(records)
        self.logger.info(f"Generated {len(records)} customer records")

        return GeneratedData(
            table_name=self.table_name,
            data=df,
            surrogate_keys=keys
        )
